version: '3.8'
services:

  db:
    image: postgres:latest
    container_name: db
    restart: on-failure
    environment:
      POSTGRES_DB: docflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/1.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/2.sql
    ports:
      - "5433:5432"
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: on-failure
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: on-failure
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # sudo docker exec -it mongo_db mongosh -u mongo -p mongo document_db
  mongo_db:
    image: mongo:6-jammy
    container_name: mongo_db
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: document_db
    ports:
      - '27017:27017'
    volumes:
      - ./mongo/init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  elastic:
    image: elasticsearch:7.10.1
    logging:
      driver: "json-file"
      options:
        max-size: "1000m"
        max-file: "10"
    container_name: elastic
    environment:
      - discovery.type=single-node
      - node.name=odfe-node
      - discovery.seed_hosts=odfe-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9600:9600"
  # logstash:
  #   user: root
  #   image: logstash:7.17.20
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "100m"
  #       max-file: "3"
  #   ports:
  #     - "5044:5044"
  #   depends_on:
  #     - mongo_db
  #     - elastic
  #   environment:
  #     - PIPELINE_WORKERS=1
  #     - PIPELINE_BATCH_SIZE=125
  #     - PIPELINE_BATCH_DELAY=50
  #   volumes:
  #     - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
