spring:
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/docflow
  jpa:
    prnoperties.hiberate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
      format_sql: true
      hdm2ddl.auto: validate
      open-in-vew: false
