spring:
  application:
    name: docflow
  profiles:
    include:
    - 'db'
    - 'oauth2'

security.bcrypt.costFactor: 4

logging.level.com.docflow: DEBUG

# TODO organize everything

data.server.port: 9000


spring.kafka:
  bootstrap-servers: localhost:9092
  consumer.group-id: main-server-consumer-group

service.data.kafka:
  topic-to: 'toDataService'
  topic-from: 'fromDataService'
